market:
  - US
  - SE
  - GB
  - BE
  - PT

playlist_dict:
  SE: "7jmQBEvJyGHPqKEl5UcEe9"
  GB: "37i9dQZEVXbLnolsZ8PSNw"
  BE: "37i9dQZEVXbJNSeeHswcKB"
  US: "37i9dQZEVXbLRQDuF5jeBp"
  PT: "37i9dQZEVXbKyJS56d1pgi"

pipelines:
  name: "pipelines"
  config: 
    log_folder_path: "./etl_project/logs"
    artist_id_folder_path: "etl_project/data/top_artist_from_global50.csv"
  schedule:
    run_minutes: 0.1
    poll_seconds: 0.2

pipeline_sql:
  name: "pipeline_sql"
  config: 
    extract_template_path: "./etl_project/assets/sql/extract"
    transform_template_path: "./etl_project/assets/sql/transform"
    log_folder_path: "./etl_project/logs"
  schedule:
    run_seconds: 5
    poll_seconds: 2
